name: ci

on:
  push:
    branches:
      - dev
    paths:
     - .github/workflows/ci.yaml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "running tests"

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - run: echo "building app"

  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run Hello World JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "GitHub Actions Student"